apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: queercoded-issuer
  namespace: cert-manager
spec:
  acme:
    email: "queercoded.dev-letsencrypt.com@diademiemi.me"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-queercoded
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token